\copy raw.sale_source FROM '/data/MOCK_DATA.csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy raw.sale_source FROM '/data/MOCK_DATA (1).csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy raw.sale_source FROM '/data/MOCK_DATA (2).csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy raw.sale_source FROM '/data/MOCK_DATA (3).csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy raw.sale_source FROM '/data/MOCK_DATA (4).csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy raw.sale_source FROM '/data/MOCK_DATA (5).csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy raw.sale_source FROM '/data/MOCK_DATA (6).csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy raw.sale_source FROM '/data/MOCK_DATA (7).csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy raw.sale_source FROM '/data/MOCK_DATA (8).csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy raw.sale_source FROM '/data/MOCK_DATA (9).csv' WITH (FORMAT csv, HEADER true, NULL '')

-- Source id restarts in every CSV, so assign a unique key after the append.
ALTER TABLE raw.sale_source
    ADD COLUMN source_row_id bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE raw.sale_source
    ADD CONSTRAINT sale_source_pk PRIMARY KEY (source_row_id);
